---
title: "p8105_hw5_as6183"
output: github_document
---
# Problem 1:

```{r}
data = read.csv("C:/Users/13038/Downloads/homicide-data.csv") 
```

**Description of Raw Data:**

```{r}
library(tidyverse)
data = data%>%
  mutate(city_state = paste(city,state,sep=", "))

tab_1 = data%>%
  group_by(city_state)%>%
  summarise("Total Number of Homicides" = n())

tab_2 = data%>%
  group_by(city_state)%>%
  filter(disposition != "Closed by arrest")%>%
  summarise("Number of unsolved homicides" = n())

tab_final = merge(tab_1,tab_2,by = "city_state")%>%
  dplyr::arrange(desc(`Total Number of Homicides`))

tab_final%>%
  knitr::kable()
```

```{r}
colnames(tab_final) = c("city_state","Total","Unsolved")

Baltimore_Unsolved = tab_final%>%
   filter(city_state == "Baltimore, MD")

 Unsolved_Prop_Bmore =
   prop.test(
             pull(Baltimore_Unsolved,`Unsolved`),
             pull(Baltimore_Unsolved,`Total`)
     )%>%
   broom::tidy()%>%
   select(estimate,conf.low,conf.high)%>%
   mutate(city_state = pull(Baltimore_Unsolved,city_state))%>%
   select(city_state,estimate,conf.low,conf.high)



prop_test_func = function(data) {
  prop.test(pull(data,Unsolved),pull(data,Total))%>%
    broom::tidy()%>%
    select(estimate,conf.low,conf.high)
}
 
 Unsolved_Prop_Final = tab_final%>%
   group_by(city_state)%>%
   mutate(Total = as.double(Total), Unsolved = as.double(Unsolved))%>%
   nest()%>%
  mutate(prop_unsolved = map(data, prop_test_func))%>%
   unnest()%>%
   arrange(estimate)
  
 Unsolved_Prop_Final%>%
   ggplot(aes(x = reorder(city_state,estimate), y = estimate)) +
   geom_bar(stat="identity")+
   geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
   xlab("City")+
   ylab("Estimate of the Proportion of Unsolved Murders")+
   ggtitle("Estimate for the Proportion of Unsolved Murders for each City")+
   theme(axis.text.x = element_text(size=8,angle=90,vjust = 0.5, hjust = 1),plot.title=element_text(size=11))
```

# Problem 2:

```{r}

setwd("./data")
files = list.files(".")
data = purrr::map_dfr(files,read.csv)%>%
  mutate(id = c(paste0("Control"," ",seq(1,10)),paste0("Experiment"," ",seq(1,10))))%>%
  pivot_longer(week_1:week_8,names_to="week",values_to = "observations")%>%
  mutate(week = recode(week,week_1 = "1", week_2 = "2", week_3 = "3", week_4 = "4", week_5 = "5", week_6 = "6", week_7 = "7", week_8 = "8"))%>%
  mutate(week = as.numeric(week))

ggplot(data,aes(x = week, y = observations, color = id)) +
          geom_line() +
          theme_bw()+
          ggtitle("Observation over time for each subject")+
          theme(legend.title = element_blank(),legend.text = element_text(size=9))



```

# Problem 3:
```{r}
library(patchwork)

n = 30
sd = 5
mu = 0
set.seed(234)
sim_mean_sd = function(n,mu ,sd) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sd),
  )
  
  t_test = t.test(pull(sim_data,x), mu = mu)%>%
    broom::tidy()%>%
    dplyr::select(p.value)
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      p_val = t_test
    )
}

sim_results = 
  rerun(5000, sim_mean_sd(30, 0, 5)) %>% 
  bind_rows()

sim_results_diff_mus = 
  tibble(mu = seq(0,6)) %>% 
  mutate(
    output_lists = map(.x = mu, ~rerun(5000, sim_mean_sd(n = 30,mu = .x, sd = 5))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)

num_rej = sim_results_diff_mus%>%
  group_by(mu)%>%
  filter(p_val<0.05)%>%
  summarize(n_rej = n())


df = num_rej%>%
  mutate(prop_rej = n_rej/5000)

df%>%
  ggplot(aes(mu,prop_rej))+
  geom_point()+
  ggtitle("mu vs proportion of times null was rejected")+
  xlab("True Value of mu")+
  ylab("Proportion of Times Null Was Rejected")+
  theme(title = element_text(size=10))



plot_1 = sim_results_diff_mus%>%
  group_by(mu)%>%
  summarise(avg_mu_hat = mean(mu_hat))%>%
  ggplot(aes(mu,avg_mu_hat))+
  geom_point()+
  ggtitle("mu vs Average estimate of mu")+
  xlab("True Value of mu")+
  ylab("Average estimate of mu")+
  theme(title = element_text(size=10))

plot_2 = sim_results_diff_mus%>%
  filter(p_val<0.05)%>%
  group_by(mu)%>%
  summarise(avg_mu_hat = mean(mu_hat))%>%
  ggplot(aes(mu,avg_mu_hat))+
  geom_point()+
  ggtitle("mu vs Average estimate of mu when H_0 was rejected")+
  xlab("True Value of mu")+
  ylab("Average estimate of mu")+
  theme(title = element_text(size=8))

plot_1 + plot_2
```
